name = "private-access-to-gcs"
main = "src/worker.js"
compatibility_date = "2023-05-30"

[vars]
# The necessary secrets are:
# - GCS_BUCKET
# - GCS_ACCESS_KEY_ID
# - GCS_SECRET_ACCESS_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
